### ISSUE TITLE
Subprocess.check_call()

### ISSUE THREAD

**Issue by SimonNgj** [ScazLab/task-models#6]
```
simon@simon:~/MyTest/task-models/samples$ python icra_scenario2pomdp.py
Traceback (most recent call last):
  File "icra_scenario2pomdp.py", line 18, in <module>
    gp = p.solve(method='grid', n_iterations=500, verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/task_models/lib/pomdp.py", line 363, in solve
    stdout=None if verbose else DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
Here is the error I got when I try to run: python icra_scenario2pomdp.py on the terminal
Note: I installed the POMDP solver and copied the pomdp-sol into  ../task-models/samples

**Comment by omangin** [comment]
Hi @SimonNgj. By default, the software expects the `pomdp-solve` binary to be located in your `$PATH`.

If you used the commands from the [README](https://github.com/ScazLab/task-models#prerequisites) you need to make sure that `~/.local` is in your `$PATH`.

Alternatively it's also possible to use the binary in the `sample` directory but you need to add the `sample` directory to your `$PATH`,

  ````bash
  export PATH="$HOME/MyTest/task-models/samples/:$PATH"
  ````

In addition, I'll add a more meaningful error message when the solver binary cannot be found.

**[EDIT]** My bad, actually, there is already a check for the executable being found, so it seems that the issue is something else. Can you add the following line after line 16 in `icra_scenario2pomdp.py`, run it again, and post the output?

  ````python
  print('Solver path: {}'.format(p._solver_path))
  ````

**Comment by SimonNgj** [comment]
My problem is solved now. Thank you so much @omangin. You're right. I just add 
`export PATH="$HOME/MyTest/task-models/samples/:$PATH"`
before running: python icra_scenario2pomdp.py

Output: ....
```
Epoch: 498...7 vectors in 0.00 secs. (1.27 total) (err=1.00e-01)
Epoch: 499...7 vectors in 0.01 secs. (1.28 total) (err=1.00e-01)
Epoch: 500...7 vectors in 0.00 secs. (1.28 total) (err=1.00e-01)
++++++++++++++++++++++++++++++++++++++++
Solution found.  See file:
	tosolve.alpha
	tosolve.pg
++++++++++++++++++++++++++++++++++++++++
User time = 0 hrs., 0 mins, 1.23 secs. (= 1.23 secs)
System time = 0 hrs., 0 mins, 0.05 secs. (= 0.05 secs)
Total execution time = 0 hrs., 0 mins, 1.28 secs. (= 1.28 secs)
```
However, I don't know where do tosolve.alpha and tosolve.pg locate!!!

**Comment by omangin** [comment]
To answer your last question, they are generated in a temporary directory and deleted after being loaded by the code. You can check that in the source code of the [`solve`](https://github.com/ScazLab/task-models/blob/master/task_models/lib/pomdp.py#L338) method and eventually modify it if you need the files to be kept elsewhere.
